###
POST http://localhost:8080/file/operationFile
Content-Type: application/json

{
  "fileName": "E:\\qiandu_netdisk_download\\206-陈天 · Rust 编程第一课",
  "includeFolder": true,
  "fileOperator": "rename",
  "condition": "[一手资源：666java.com]"
}
